### PR TITLE
Add DisableTypeGuessing option

### PR DESCRIPTION
**Pull request by erri120**

### CODE REVIEW

**Review by xPaw — APPROVED** [review]
I think this is an okay (but not ideal of course) option until we figure out what to do with the types.

I would however add a warning in the xmldoc that this option *may* disappear in the future.

**Comment by yaakov-h** [comment]
I don't feel like this solves the actual problem, but it also has no tests at all as codecov warned above.

**Comment by erri120** [comment]
Added some tests.

**Comment by xPaw** [comment]
Can you try latest version of the library to see if your use case still warrants an option to disable type guessing?

**Comment by erri120** [comment]
> Can you try latest version of the library to see if your use case still warrants an option to disable type guessing?

Yes, I still want to disable type guessing and do custom `string -> other` conversions.

**Comment by xPaw** [comment]
You should be able to with ToString() or `public string ....`, no?

**Comment by erri120** [comment]
> You should be able to with ToString() or `public string ....`, no?

As explained in-depth in #53, if type guessing is broken, even `.ToString` won't help. Furthremore, doing custom parsing of the raw string values allows my lib to produce better error message, if something goes wrong.

I don't really see the issue with adding a new, non-default option to disable a "controversial feature".

**Comment by xPaw** [comment]
But I am asking if it's still broken for you, because last release fixes numbers incorrectly parsing into floats.

**Comment by erri120** [comment]
> But I am asking if it's still broken for you, because last release fixes numbers incorrectly parsing into floats.
> 
> Do you have a real use case where current state of things doesn't let you do something?

#77 has fixed #73 and #53. The 64-bit unsigned integer number for `LastOwner` in app manifest files is now being parsed as a `string`. Again, this isn't just about fixing the issue, this is about disabling type guessing completely, not because it's still broken but because it's useless. It should be clear from my ranting in #53 that I don't see any value in type guessing and matching Valve's behavior, which is why I opened this PR. Those who want type guessing have it by default and those that don't see any value in it can disable it optionally.

**Comment by xPaw** [comment]
Putting 'being useless' argument aside, do you currently experience an issue where you *have* to disable it?

**Comment by erri120** [comment]
I'm gonna close this PR, we're walking in circles and going nowhere.

**Pull request closed without merging**
